version: '3'

services:
  database:
    container_name: galp-main-api
    env_file:
      - ./main-api/.env
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}    
    volumes:
      - ./docker-volume/postgres:/var/lib/postgresql/data
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4:6.10
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=johndoe@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    links:
      - database
    networks:
      - network
      
  redis:
    image: redis:latest
    container_name: gap-main-api-redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./docker-volume/redis:/data
    restart: always
    command: redis-server --appendonly yes
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./docker-volume/rabbitmq_data:/var/lib/rabbitmq
    networks:
      - network

networks:
  network:
    driver: bridge